/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlpRouteImport } from './routes/plp'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditAuditIdRouteImport } from './routes/audit.$auditId'

const PlpRoute = PlpRouteImport.update({
  id: '/plp',
  path: '/plp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditAuditIdRoute = AuditAuditIdRouteImport.update({
  id: '/audit/$auditId',
  path: '/audit/$auditId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audits': typeof AuditsRoute
  '/plp': typeof PlpRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audits': typeof AuditsRoute
  '/plp': typeof PlpRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audits': typeof AuditsRoute
  '/plp': typeof PlpRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/audits' | '/plp' | '/audit/$auditId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/audits' | '/plp' | '/audit/$auditId'
  id: '__root__' | '/' | '/$' | '/audits' | '/plp' | '/audit/$auditId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuditsRoute: typeof AuditsRoute
  PlpRoute: typeof PlpRoute
  AuditAuditIdRoute: typeof AuditAuditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plp': {
      id: '/plp'
      path: '/plp'
      fullPath: '/plp'
      preLoaderRoute: typeof PlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$auditId': {
      id: '/audit/$auditId'
      path: '/audit/$auditId'
      fullPath: '/audit/$auditId'
      preLoaderRoute: typeof AuditAuditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuditsRoute: AuditsRoute,
  PlpRoute: PlpRoute,
  AuditAuditIdRoute: AuditAuditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
